### ISSUE TITLE
Support `timeout_seconds` or passing kwargs to tls-client

### ISSUE THREAD

**Issue by gerryfletch** [daan-dj/TurboGpt#1]
Hello, "complex" or long messages may take longer than the [default](https://github.com/FlorianREGAZ/Python-Tls-Client/blob/bda8a0f1ce12ab26b578bf1be71b226a2806b561/tls_client/sessions.py#L278) `30` seconds in `tls-client`. Would be useful to add it as an argument in `send_message`, or permit `kwargs` that get passed into `session.post`

**Comment by gerryfletch** [comment]
I experimented changing this locally but it didn't appear to have much effect passing it through to [`python-tls-client`](https://github.com/FlorianREGAZ/Python-Tls-Client/) so I instead modified the underlying [call to `tls-client`](https://github.com/FlorianREGAZ/Python-Tls-Client/blob/bda8a0f1ce12ab26b578bf1be71b226a2806b561/tls_client/sessions.py#L352) to configure a more appropriate timeout and that seemed to work.

Thanks for the lib!

**Comment by daan-dj** [comment]
thank you for taking interest in my project. Thank you for the tls-client lib!.

**Comment by gerryfletch** [comment]
Fine to close, seems it is an issue with `python-tls-client` not propagating the varg properly :)
